version: "3.8"
 rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq-asid.asiddeploy.com
    ports:
      - "8093:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json

