version: "3.8"

services:
 club_rep:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: paswword
      MYSQL_DATABASE: school_db
    ports:
      - "3311:3306"
    networks:
      - my-db-network

 club-service:
    image: club:latest  # Replace with your image name
    ports:
      - "8087:8087"  # Map container port to host port
    networks:
      - my-db-network
    environment:
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: 141.145.213.246:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: 141.145.213.246:9092
      SPRING_KAFKA_CONSUMER_GROUP-ID: myGroup
      SPRING_DATASOURCE_URL: jdbc:mysql://club_rep:3306/school_db?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://158.178.206.119:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: 141.145.207.150
      EUREKA_INSTANCE_IP_ADDRESS: 141.145.207.150
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true 
    depends_on:
      - club_rep
    restart: always

networks:
  my-db-network:
    driver: bridge
 