version: "3.8"

services:
  view_rep:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: paswword
      MYSQL_DATABASE: school_db
    ports:
      - "3312:3306"
    networks:
      - my-db-network

  view-service:
    image: view:latest  # Replace with your image name
    ports:
      - "8089:8089"  # Map container port to host port
    networks:
      - my-db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://view_rep:3306/school_db?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://158.178.206.119:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: 141.145.203.31
      EUREKA_INSTANCE_IP_ADDRESS: 141.145.203.31
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    depends_on:
      - view_rep
    restart: always

networks:
  my-db-network:
    driver: bridge